<a href="https://colab.research.google.com/github/citydataviz/FastCampus/blob/main/%08(%E1%84%80%E1%85%AA%E1%84%8C%E1%85%A6)_%E1%84%83%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A5%E1%84%87%E1%85%AE%E1%86%AB%E1%84%89%E1%85%A5%E1%86%A8_%E1%84%91%E1%85%B5%E1%86%AF%E1%84%89%E1%85%AE%E1%84%85%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%87%E1%85%B3%E1%84%85%E1%85%A5%E1%84%85%E1%85%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 콜랩 샘플 데이터 불러오기

- california_housing_test.csv 파일을 읽어보자.
- pandas 라이브러리를 pd로 수정해서 사용
- 힌트: pd.read_csv 사용

In [ ]:
# 데이터프레임을 df 변수이름으로 저장

In [ ]:
# 첫번째 5개 행 읽기 (head)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
# 2. 기본 정보 확인 (info, describe)

2. 데이터 기본 정보:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

데이터 통계 정보:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [ ]:
# 3. 위도(latitude)와 경도(latitude) 컬럼만 별도로 뽑아내기

      latitude  longitude
0        37.37    -122.05
1        34.26    -118.30
2        33.78    -117.81
3        33.82    -118.36
4        36.33    -119.67
...        ...        ...
2995     34.42    -119.86
2996     34.06    -118.14
2997     36.30    -119.70
2998     34.10    -117.12
2999     34.42    -119.63

[3000 rows x 2 columns]

In [ ]:
# 4. 조건부 필터링

중간 주택 가격이 300,000달러 이상인 지역:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
18,-118.88,34.21,26.0,1590.0,196.0,654.0,199.0,6.5851,300000.0
19,-122.59,38.01,35.0,8814.0,1307.0,3450.0,1258.0,6.1724,414300.0
25,-118.03,34.16,36.0,1401.0,218.0,667.0,225.0,7.1615,484700.0
...,...,...,...,...,...,...,...,...,...
2983,-122.54,37.90,48.0,2491.0,460.0,937.0,455.0,4.4375,370000.0
2987,-121.97,37.29,25.0,4096.0,743.0,2027.0,741.0,5.3294,300300.0
2992,-122.33,37.39,52.0,573.0,102.0,232.0,92.0,6.2263,500001.0
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
# 5. 새로운 열 만들기
# 방당 인구수 계산

방당 인구수를 추가한 데이터:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,population_per_room
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,0.395624
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,0.535762
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,0.413486
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,0.731343
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,0.684932
...,...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0,0.867586
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0,0.665018
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0,0.724895
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0,0.479167
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,0.426629

In [ ]:
# 7. 데이터 정렬

주택 가격 기준 내림차순 정렬:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,population_per_room
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,0.426629
2053,-122.25,37.45,34.0,2999.0,365.0,927.0,369.0,10.2811,500001.0,0.309103
117,-122.07,37.34,30.0,1851.0,238.0,631.0,236.0,10.1007,500001.0,0.340897
118,-117.18,33.02,15.0,3540.0,453.0,1364.0,425.0,13.6623,500001.0,0.385311
2152,-118.43,33.96,20.0,1901.0,270.0,704.0,254.0,8.7819,500001.0,0.370331
...,...,...,...,...,...,...,...,...,...,...
2555,-122.06,37.39,22.0,1236.0,290.0,413.0,274.0,3.6875,40000.0,0.334142
734,-117.65,35.00,36.0,1184.0,316.0,672.0,241.0,1.9107,39800.0,0.567568
2740,-119.97,36.44,18.0,1128.0,237.0,772.0,220.0,2.1771,39200.0,0.684397
1031,-123.08,40.40,10.0,365.0,102.0,140.0,49.0,1.7969,37500.0,0.383562
2001,-117.16,32.71,52.0,845.0,451.0,1230.0,375.0,1.0918,22500.0,1.455621

## 시각화 라이브러리 pygwalker
- Tableau 와 유사한 기능을 파이썬에서 실행가능
- Link: https://github.com/Kanaries/pygwalker

In [ ]:
# pygwaker 설치 (pip install + 패키지)

Collecting pygwalker
  Downloading pygwalker-0.4.9.13-py3-none-any.whl.metadata (20 kB)
Collecting anywidget (from pygwalker)
  Downloading anywidget-0.9.13-py3-none-any.whl.metadata (7.2 kB)
Collecting appdirs (from pygwalker)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting arrow (from pygwalker)
  Downloading arrow-1.3.0-py3-none-any.whl.metadata (7.5 kB)
Collecting astor (from pygwalker)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: cachetools in /usr/local/lib/python3.10/dist-packages (from pygwalker) (5.5.0)
Requirement already satisfied: duckdb<2.0.0,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from pygwalker) (1.1.3)
Collecting gw-dsl-parser==0.1.49.1 (from pygwalker)
  Downloading gw_dsl_parser-0.1.49.1-py3-none-any.whl.metadata (1.2 kB)
Collecting ipylab<=1.0.0 (from pygwalker)
  Downloading ipylab-1.0.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from pygwalker) (7.34.0)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.10/dist-packages (from pygwalker) (7.7.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from pygwalker) (3.1.4)
Collecting kanaries-track==0.0.5 (from pygwalker)
  Downloading kanaries_track-0.0.5-py3-none-any.whl.metadata (913 bytes)
Requirement already satisfied: numpy<2.0.0 in /usr/local/lib/python3.10/dist-packages (from pygwalker) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pygwalker) (24.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pygwalker) (2.2.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from pygwalker) (5.9.5)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (from pygwalker) (17.0.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.10/dist-packages (from pygwalker) (2.10.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from pygwalker) (2024.2)
Collecting quickjs (from pygwalker)
  Downloading quickjs-1.19.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (590 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from pygwalker) (2.32.3)
Collecting segment-analytics-python==2.2.3 (from pygwalker)
  Downloading segment_analytics_python-2.2.3-py2.py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pygwalker) (2.0.36)
Requirement already satisfied: sqlglot>=23.15.8 in /usr/local/lib/python3.10/dist-packages (from pygwalker) (25.1.0)
Requirement already satisfied: traitlets in /usr/local/lib/python3.10/dist-packages (from pygwalker) (5.7.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from pygwalker) (4.12.2)
Collecting wasmtime>=12.0.0 (from gw-dsl-parser==0.1.49.1->pygwalker)
  Downloading wasmtime-28.0.0-py3-none-manylinux1_x86_64.whl.metadata (7.5 kB)
Collecting backoff>=2.2.1 (from kanaries-track==0.0.5->pygwalker)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting dateutils>=0.6.12 (from kanaries-track==0.0.5->pygwalker)
  Downloading dateutils-0.6.12-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting monotonic~=1.5 (from segment-analytics-python==2.2.3->pygwalker)
  Downloading monotonic-1.6-py2.py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: python-dateutil~=2.2 in /usr/local/lib/python3.10/dist-packages (from segment-analytics-python==2.2.3->pygwalker) (2.8.2)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->pygwalker) (5.5.6)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->pygwalker) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->pygwalker) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->pygwalker) (3.0.13)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython->pygwalker) (75.1.0)
Collecting jedi>=0.16 (from ipython->pygwalker)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython->pygwalker) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->pygwalker) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->pygwalker) (3.0.48)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->pygwalker) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->pygwalker) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->pygwalker) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->pygwalker) (4.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->pygwalker) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->pygwalker) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->pygwalker) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->pygwalker) (2024.12.14)
Collecting psygnal>=0.8.1 (from anywidget->pygwalker)
  Downloading psygnal-0.11.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Collecting types-python-dateutil>=2.8.10 (from arrow->pygwalker)
  Downloading types_python_dateutil-2.9.0.20241206-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->pygwalker) (3.0.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->pygwalker) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic->pygwalker) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in /usr/local/lib/python3.10/dist-packages (from pydantic->pygwalker) (2.27.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pygwalker) (3.1.1)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets->pygwalker) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets->pygwalker) (6.3.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->pygwalker) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->pygwalker) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->pygwalker) (0.2.13)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil~=2.2->segment-analytics-python==2.2.3->pygwalker) (1.17.0)
Requirement already satisfied: importlib_resources>=5.10 in /usr/local/lib/python3.10/dist-packages (from wasmtime>=12.0.0->gw-dsl-parser==0.1.49.1->pygwalker) (6.4.5)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (6.5.5)
Requirement already satisfied: pyzmq<25,>=17 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (24.0.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (23.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (5.7.2)
Requirement already satisfied: nbformat in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (7.16.4)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.6.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.21.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.1.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.6.1->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (4.3.6)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.10.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.5.1)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.10/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (2.21.1)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.10/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (4.23.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.10/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (21.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.5.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (0.22.3)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.10/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.24.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (2.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (2.22)
Requirement already satisfied: anyio<4,>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (3.7.1)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.10/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.8.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->pygwalker) (1.2.2)
Downloading pygwalker-0.4.9.13-py3-none-any.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 41.2 MB/s eta 0:00:00
Downloading gw_dsl_parser-0.1.49.1-py3-none-any.whl (956 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 956.2/956.2 kB 46.6 MB/s eta 0:00:00
Downloading kanaries_track-0.0.5-py3-none-any.whl (8.6 kB)
Downloading segment_analytics_python-2.2.3-py2.py3-none-any.whl (24 kB)
Downloading ipylab-1.0.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.2/100.2 kB 7.6 MB/s eta 0:00:00
Downloading anywidget-0.9.13-py3-none-any.whl (213 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.7/213.7 kB 15.3 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading arrow-1.3.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 5.0 MB/s eta 0:00:00
Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Downloading quickjs-1.19.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 59.4 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading dateutils-0.6.12-py2.py3-none-any.whl (5.7 kB)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 62.1 MB/s eta 0:00:00
Downloading monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Downloading psygnal-0.11.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (727 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 727.4/727.4 kB 37.2 MB/s eta 0:00:00
Downloading types_python_dateutil-2.9.0.20241206-py3-none-any.whl (14 kB)
Downloading wasmtime-28.0.0-py3-none-manylinux1_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 80.4 MB/s eta 0:00:00
Installing collected packages: quickjs, monotonic, appdirs, wasmtime, types-python-dateutil, psygnal, jedi, backoff, astor, segment-analytics-python, gw-dsl-parser, dateutils, arrow, kanaries-track, ipylab, anywidget, pygwalker
Successfully installed anywidget-0.9.13 appdirs-1.4.4 arrow-1.3.0 astor-0.8.1 backoff-2.2.1 dateutils-0.6.12 gw-dsl-parser-0.1.49.1 ipylab-1.0.0 jedi-0.19.2 kanaries-track-0.0.5 monotonic-1.6 psygnal-0.11.1 pygwalker-0.4.9.13 quickjs-1.19.4 segment-analytics-python-2.2.3 types-python-dateutil-2.9.0.20241206 wasmtime-28.0.0

In [ ]:
# 설치 후 import + 라이브러리명

import pygwalker as pyg
pyg.walk(df)